/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function printf(a: number, b: number): number;
export function puts(a: number): number;
export function putchar(a: number): number;
export function gettimeofday(a: number, b: number): number;
export function set_panic_hook(): void;
export function __wbg_calculator_free(a: number): void;
export function libusb_get_device(a: number): number;
export function libusb_ref_device(a: number): number;
export function libusb_unref_device(a: number): void;
export function calculator_new(a: number, b: number, c: number, d: number): number;
export function calculator_update(a: number): number;
export function calculator_list_dir(a: number, b: number, c: number): number;
export function calculator_download_file(a: number, b: number, c: number, d: number): number;
export function calculator_upload_file(a: number, b: number, c: number, d: number, e: number): void;
export function calculator_upload_os(a: number, b: number, c: number): void;
export function calculator_delete_file(a: number, b: number, c: number): void;
export function calculator_delete_dir(a: number, b: number, c: number): void;
export function calculator_create_dir(a: number, b: number, c: number): void;
export function calculator_copy_file(a: number, b: number, c: number, d: number, e: number): void;
export function calculator_move_file(a: number, b: number, c: number, d: number, e: number): void;
export function libusb_release_interface(a: number, b: number): number;
export function libusb_close(a: number): void;
export function libusb_get_device_descriptor(a: number, b: number): number;
export function strncpy(a: number, b: number, c: number): number;
export function malloc(a: number): number;
export function realloc(a: number, b: number): number;
export function free(a: number): void;
export function memchr(a: number, b: number, c: number): number;
export function strlen(a: number): number;
export function libusb_init(a: number): number;
export function libusb_exit(a: number): void;
export function libusb_set_configuration(a: number, b: number): number;
export function libusb_reset_device(a: number): number;
export function libusb_claim_interface(a: number, b: number): number;
export function libusb_get_active_config_descriptor(a: number, b: number): number;
export function libusb_free_config_descriptor(a: number): void;
export function libusb_bulk_transfer(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function libusb_get_version(): number;
export function libusb_has_capability(a: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
