[package]
name = "n-link"
version = "0.1.6"
description = "Free, cross-platform, CX-II compatible computer linking program for the TI-Nspire"
authors = [ "Ben Schattinger <developer@lights0123.com>" ]
license = "GPL-3.0"
repository = "https://github.com/lights0123/n-link"
default-run = "n-link"
edition = "2018"
build = "src/build.rs"

[dependencies]
anyhow = "1.0.32"
serde_json = "1.0"
libnspire = "0.2.2"
lazy_static = "1.4.0"
rusb = "0.9"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "1.5.4", features = ["dialog-open", "shell-open"] }
clap = "3.0.0-beta.2"
indicatif = "0.15"
libusb1-sys = { version = "0.6", features = [ "vendored" ] }
hashbrown = "0.11"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
default = [ "custom-protocol" ]

[[bin]]
name = "n-link"
path = "src/main.rs"
